name: data_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pandas
  - numpy
  - matplotlib
  - seaborn
  - scikit-learn
  - scipy
  - xgboost
  - lightgbm
  - geopandas
  - folium
  - branca
  - jupyter
  - ipykernel
  - notebook
